import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'de' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation  
    'nav.dashboard': 'Dashboard',
    'nav.vocabulary': 'Vocabulary',
    'nav.wordDossier': 'Word Dossier',
    'nav.sentence': 'Sentences',
    'nav.writing': 'Writing',
    'nav.exercises': 'Exercises',
    'nav.memorizer': 'Memorizer',
    'nav.wordAssociation': 'Word Association',
    'nav.conversation': 'Conversation',
    'nav.highlighter': 'Highlighter',
    'nav.diary': 'Mistake Diary',
    'nav.review': 'Review',
    'nav.activityLog': 'Activity Log',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    'nav.aiCompanion': 'AI Companion',
    'nav.telcExam': 'TELC B2 Exam',
    'nav.telcPrep': 'TELC Prep',
    'nav.history': 'History & Export',
    'nav.foundations': 'Foundations',
    'nav.practice': 'Practice',
    'nav.communication': 'Communication',
    'nav.progress': 'Progress',
    'nav.telcB2': 'TELC B2',
    'nav.learningPath': 'Learning Path',
    'nav.achievements': 'Achievements',
    'nav.masteryCourse': 'Mastery Course',
    'nav.certificates': 'Certificates',
    'nav.serverStatus': 'Server Status',
    'nav.allSystemsOperational': 'All Systems Operational',
    'nav.performanceDegraded': 'Performance Degraded',
    'nav.serviceUnavailable': 'Service Unavailable',
    'nav.database': 'Database',
    'nav.apiLatency': 'API Latency',
    'nav.authService': 'Auth Service',
    'nav.online': 'Online',
    'nav.down': 'Down',
    'nav.active': 'Active',
    'nav.lastChecked': 'Last checked',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome back',
    'dashboard.subtitle': 'Continue your German learning journey. Track your progress and unlock new achievements.',
    'dashboard.wordsLearned': 'Words Learned',
    'dashboard.exercisesDone': 'Exercises Done',
    'dashboard.currentStreak': 'Current Streak',
    'dashboard.totalMistakes': 'Total Mistakes',
    'dashboard.weeklyActivity': 'Weekly Activity',
    'dashboard.weakSpots': 'Areas Needing Focus',
    'dashboard.recommendations': 'Recommended Next Steps',
    'dashboard.mistakeDistribution': 'Mistake Distribution',
    'dashboard.keepGoing': '🔥 Keep it going!',
    'dashboard.learningOpportunities': 'Learning opportunities',
    'dashboard.noWeakSpots': 'No weak spots identified yet. Keep practicing!',
    'dashboard.goal': 'Goal',
    'dashboard.words': 'words',
    'dashboard.exercises': 'exercises',
    'dashboard.errors': 'errors',
    'dashboard.aiInsights': 'AI Insights',
    'dashboard.generating': 'Generating insights...',
    'dashboard.quickActions': 'Quick Actions',
    
    // Server Status
    'server.healthy': 'All Systems Operational',
    'server.degraded': 'Degraded Performance',
    'server.down': 'System Down',
    
    // Theme
    'theme.light': 'Light Mode',
    'theme.dark': 'Dark Mode',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.close': 'Close',
    'common.send': 'Send',
    'common.retry': 'Retry',
    'common.confirm': 'Confirm',
    'common.noData': 'No data available',
    'common.searchPlaceholder': 'Search...',
    'common.days': 'days',
    'common.hours': 'hours',
    'common.minutes': 'minutes',
    'common.seconds': 'seconds',
    'common.points': 'points',
    'common.level': 'Level',
    'common.xp': 'XP',
    'common.streak': 'Streak',
    'common.startNow': 'Start Now',
    'common.viewAll': 'View All',
    'common.learnMore': 'Learn More',
    
    // Toast messages
    'toast.saved': 'Saved successfully',
    'toast.deleted': 'Deleted successfully',
    'toast.error': 'Something went wrong',
    'toast.pleaseLogin': 'Please log in first',
    'toast.copied': 'Copied to clipboard',
    'toast.added': 'Added successfully',
    'toast.updated': 'Updated successfully',
    'toast.generating': 'Generating...',
    'toast.analyzing': 'Analyzing...',
    
    // Empty states
    'empty.noResults': 'No results found',
    'empty.noItems': 'No items yet',
    'empty.startPracticing': 'Start practicing to see your progress!',
    'empty.noMistakes': 'No mistakes found - keep practicing!',
    'empty.noCertificates': 'Complete modules to earn certificates',
    'empty.noAchievements': 'Start learning to unlock achievements',
    
    // Auth
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.signOut': 'Sign Out',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.forgotPassword': 'Forgot password?',
    'auth.noAccount': "Don't have an account?",
    'auth.haveAccount': 'Already have an account?',
    'auth.signInToFluentPass': 'Sign In to FluentPass',
    'auth.createFreeAccount': 'Create Free Account',
    'auth.processing': 'Processing...',
    
    // Sentence Generator
    'sentence.title': 'Sentence Generator',
    'sentence.subtitle': 'Generate German sentences for practice',
    'sentence.difficulty': 'Difficulty Level',
    'sentence.topic': 'Topic (optional)',
    'sentence.topicPlaceholder': 'Select a topic or leave empty',
    'sentence.noTopic': 'No specific topic',
    'sentence.customTopic': 'Custom Topic...',
    'sentence.customTopicPlaceholder': 'Enter your own topic...',
    'sentence.grammarFocus': 'Grammar Focus (optional)',
    'sentence.grammarPlaceholder': 'Select grammar point or leave empty',
    'sentence.noGrammar': 'No specific grammar',
    'sentence.generate': 'Generate Sentence',
    'sentence.generating': 'Generating...',
    'sentence.german': 'German',
    'sentence.english': 'English',
    'sentence.analysis': 'Grammatical Analysis',
    'sentence.generated': 'Sentence generated!',
    
    // Word Dossier
    'word.title': 'Word Dossier',
    'word.subtitle': 'Deep analysis of German words with synonyms, antonyms, and examples',
    'word.search': 'Enter a German word to analyze...',
    'word.analyze': 'Analyze',
    'word.analyzing': 'Analyzing...',
    'word.definition': 'Definition',
    'word.translation': 'Translation',
    'word.wordFamily': 'Word Family (Wortfamilie)',
    'word.prefixVerbs': 'Prefix Verbs',
    'word.synonyms': 'Synonyms',
    'word.antonyms': 'Antonyms',
    'word.examples': 'Example Sentences',
    
    // Vocabulary
    'vocabulary.title': 'Vocabulary Generator',
    'vocabulary.subtitle': 'Generate TELC B2-level vocabulary by topic',
    'vocabulary.topic': 'Topic',
    'vocabulary.customTopic': 'Custom Topic',
    'vocabulary.numberOfWords': 'Number of words',
    'vocabulary.generate': 'Generate Vocabulary',
    'vocabulary.addToReview': 'Add to Review',
    'vocabulary.added': 'Added to review!',
    
    // Exercises
    'exercises.title': 'Exercises',
    'exercises.subtitle': 'Practice with multiple choice, translation, and gap fill exercises',
    'exercises.quiz': 'Multiple Choice',
    'exercises.translation': 'Translation',
    'exercises.gapFill': 'Gap Fill',
    'exercises.generate': 'Generate Exercise',
    'exercises.checkAnswer': 'Check Answer',
    'exercises.nextExercise': 'Next Exercise',
    'exercises.correct': 'Correct!',
    'exercises.incorrect': 'Incorrect',
    'exercises.yourAnswer': 'Your answer',
    'exercises.correctAnswer': 'Correct answer',
    
    // Writing Assistant
    'writing.title': 'AI Writing Assistant',
    'writing.subtitle': 'Get expert B2-C1 level feedback on your German writing',
    'writing.prompt': 'Writing Prompt',
    'writing.selectPrompt': 'Select a prompt',
    'writing.analyze': 'Analyze Text',
    'writing.analyzing': 'Analyzing...',
    'writing.wordCount': 'words',
    'writing.overallFeedback': 'Overall Feedback',
    'writing.correctedText': 'Corrected Text',
    'writing.errors': 'Errors Found',
    'writing.noErrors': 'No significant errors found',
    
    // Memorizer
    'memorizer.title': 'The Memorizer',
    'memorizer.subtitle': 'Generate German paragraphs for memorization and practice',
    'memorizer.theme': 'Theme',
    'memorizer.selectTheme': 'Select a theme',
    'memorizer.customTheme': 'Custom theme...',
    'memorizer.generate': 'Generate Paragraph',
    'memorizer.addToReview': 'Add to Review',
    'memorizer.practice': 'Practice Writing',
    'memorizer.showAnswer': 'Show Answer',
    'memorizer.hideAnswer': 'Hide Answer',
    'memorizer.accuracy': 'Accuracy',
    
    // Word Association
    'wordAssociation.title': 'Word Association',
    'wordAssociation.subtitle': 'Test your German vocabulary with AI-generated word associations',
    'wordAssociation.startGame': 'Start Game',
    'wordAssociation.endGame': 'End Game',
    'wordAssociation.score': 'Score',
    'wordAssociation.round': 'Round',
    'wordAssociation.hint': 'Hint',
    'wordAssociation.saveWord': 'Save Word',
    'wordAssociation.explain': 'Explain',
    
    // Conversation
    'conversation.title': 'Conversation Practice',
    'conversation.subtitle': 'Practice real-life German conversations with AI',
    'conversation.scenario': 'Scenario',
    'conversation.selectScenario': 'Select a scenario',
    'conversation.startConversation': 'Start Conversation',
    'conversation.endConversation': 'End Conversation',
    'conversation.textMode': 'Text Mode',
    'conversation.voiceMode': 'Voice Mode',
    'conversation.analyzing': 'Analyzing...',
    'conversation.translate': 'Translate',
    
    // Text Highlighter
    'highlighter.title': 'Text Highlighter',
    'highlighter.subtitle': 'Paste German text and highlight vocabulary at your level',
    'highlighter.paste': 'Paste German text (e.g., news article, essay)',
    'highlighter.analyze': 'Highlight',
    'highlighter.addToReview': 'Add to Review',
    'highlighter.wordDetails': 'Word Details',
    'highlighter.vocabularyList': 'Vocabulary List',
    
    // Mistake Diary
    'diary.title': 'Mistake Diary',
    'diary.subtitle': 'Track and learn from your mistakes',
    'diary.exportPDF': 'Export PDF',
    'diary.openNewTab': 'Open in New Tab',
    'diary.totalMistakes': 'Total Mistakes',
    'diary.resolved': 'Resolved',
    'diary.active': 'Active',
    'diary.categories': 'Categories',
    'diary.completion': 'completion',
    'diary.search': 'Search mistakes...',
    'diary.showAll': 'Show All',
    'diary.showResolved': 'Show Resolved',
    'diary.all': 'All',
    'diary.listView': 'List View',
    'diary.analytics': 'Analytics',
    'diary.noMistakes': 'No mistakes found',
    'diary.tryAdjusting': 'Try adjusting your search',
    'diary.keepPracticing': 'Keep practicing to track your progress!',
    'diary.yourText': 'Your Text:',
    'diary.correction': 'Correction:',
    'diary.explanation': 'Explanation:',
    'diary.context': 'Context:',
    'diary.addNote': 'Add Note',
    'diary.editNote': 'Edit Note',
    'diary.saveNote': 'Save Note',
    'diary.notePlaceholder': 'Add your personal notes about this mistake...',
    'diary.markResolved': 'Mistake marked as resolved',
    'diary.markUnresolved': 'Marked as unresolved',
    'diary.mistakesByType': 'Mistakes by Type',
    'diary.mistakesByCategory': 'Mistakes by Category',
    'diary.autoDetecting': 'Auto-detecting mistakes...',
    'diary.autoDetect': 'Auto-Detect',
    'diary.mistakeDeleted': 'Mistake deleted successfully',
    'diary.deleteFailed': 'Failed to delete mistake',
    'diary.noContentFound': 'No content to analyze',
    'diary.completeExercises': 'Complete some exercises first',
    'diary.detected': 'Detected',
    'diary.newMistakes': 'new mistake(s)',
    'diary.noNewMistakes': 'No new mistakes detected',
    'diary.greatJob': 'Great job! Keep practicing!',
    'diary.autoDetectFailed': 'Failed to auto-detect mistakes',
    
    // Review
    'review.title': 'Review',
    'review.subtitle': 'Review vocabulary with spaced repetition',
    'review.dueItems': 'Items Due',
    'review.showAnswer': 'Show Answer',
    'review.knewIt': 'I Knew It',
    'review.needsPractice': 'Needs Practice',
    'review.noItems': 'No items due for review',
    'review.complete': 'Review Complete!',
    
    // Settings
    'settings.title': 'Settings',
    'settings.account': 'Account Information',
    'settings.email': 'Email',
    'settings.userId': 'User ID',
    'settings.apiKeys': 'API Keys',
    'settings.preferences': 'Preferences',
    'settings.audioPlayback': 'Audio Playback',
    'settings.reviewReminders': 'Review Reminders',
    'settings.savePreferences': 'Save Preferences',
    'settings.dangerZone': 'Danger Zone',
    'settings.deleteAccount': 'Delete Account',
    'settings.subscription': 'Subscription',
    'settings.manageSubscription': 'Manage Subscription',
    'settings.viewPlans': 'View Plans',
    'settings.studyStats': 'Study Statistics',
    'settings.accountCreated': 'Account created',
    'settings.lastLogin': 'Last login',
    
    // AI Companion
    'aiCompanion.title': 'AI Learning Companion',
    'aiCompanion.subtitle': 'Your personal German tutor that adapts to your level',
    'aiCompanion.startConversation': 'Start Conversation',
    'aiCompanion.starting': 'Starting...',
    'aiCompanion.listening': 'Listening...',
    'aiCompanion.processing': 'Processing...',
    'aiCompanion.textMode': 'Text Mode',
    'aiCompanion.verbalMode': 'Verbal Mode',
    'aiCompanion.analyzeMistakes': 'Analyze Mistakes',
    'aiCompanion.achievements': 'Achievements',
    'aiCompanion.aiInsights': 'AI Insights',
    'aiCompanion.learningStyle': 'Learning Style',
    'aiCompanion.strength': 'Strength',
    'aiCompanion.focusArea': 'Focus Area',
    'aiCompanion.instantFeedback': 'Instant Feedback',
    'aiCompanion.placeholder': 'Type in German or use voice...',
    'aiCompanion.voice': 'Voice',
    'aiCompanion.stop': 'Stop',
    'aiCompanion.mistakeAnalysis': 'Mistake Analysis & Suggestions',
    'aiCompanion.noErrors': 'Excellent! No significant errors found.',
    'aiCompanion.mistakesFound': 'Mistakes Found',
    'aiCompanion.alternatives': 'Alternative Ways to Say It',
    'aiCompanion.overallAssessment': 'Overall Assessment',
    'aiCompanion.recentAchievements': 'Recent Achievements',
    'aiCompanion.startChatting': 'Start chatting to unlock!',
    
    // Subscriptions
    'subscriptions.title': 'Choose Your Plan',
    'subscriptions.subtitle': 'Unlock your full potential with FluentPass Premium',
    'subscriptions.currentPlan': 'Current Plan',
    'subscriptions.upgradeNow': 'Upgrade Now',
    'subscriptions.perMonth': '/month',
    'subscriptions.popular': 'Most Popular',
    'subscriptions.features': 'What you get:',
    
    // Learning Path
    'learningPath.title': 'Your Learning Path',
    'learningPath.subtitle': 'AI-powered personalized curriculum to help you achieve TELC B2 certification',
    'learningPath.createPath': 'Create Learning Path',
    'learningPath.generateLesson': 'Generate Today\'s Lesson',
    'learningPath.dailyLesson': 'Today\'s Lesson',
    'learningPath.completed': 'Completed',
    'learningPath.tasks': 'Tasks',
    
    // Achievements
    'achievements.title': 'Achievements',
    'achievements.subtitle': 'Unlock achievements as you progress on your German learning journey',
    'achievements.totalXP': 'Total XP',
    'achievements.unlocked': 'Unlocked',
    'achievements.checkAchievements': 'Check Achievements',
    'achievements.checking': 'Checking...',
    
    // Mastery Course
    'masteryCourse.title': 'FluentPass Mastery Course',
    'masteryCourse.subtitle': 'Comprehensive 12-week program to achieve TELC B2 certification',
    'masteryCourse.modules': 'Modules',
    'masteryCourse.overview': 'Overview',
    'masteryCourse.progress': 'Course Progress',
    'masteryCourse.completed': 'completed',
    'masteryCourse.getCertificate': 'Get Course Certificate',
    
    // Certificates
    'certificates.title': 'My Certificates',
    'certificates.subtitle': 'Your earned certificates and achievements from the FluentPass Mastery Course',
    'certificates.download': 'Download',
    'certificates.share': 'Share',
    'certificates.noCertificates': 'No certificates yet',
    'certificates.startCourse': 'Start the Mastery Course to earn certificates',
    'certificates.howToEarn': 'How to earn certificates',
    
    // History
    'history.title': 'Learning History',
    'history.subtitle': 'View and export your learning progress',
    'history.exportAll': 'Export All',
    'history.vocabulary': 'Vocabulary',
    'history.exercises': 'Exercises',
    'history.writing': 'Writing',
    'history.conversations': 'Conversations',
    'history.mistakes': 'Mistakes',
    'history.memorizer': 'Memorizer',
    
    // TELC B2 Preparation
    'telc.title': 'TELC B2 Exam Preparation',
    'telc.subtitle': 'Prepare for your TELC B2 exam with interactive exercises and AI coaching',
    'telc.examSections': 'Exam Sections',
    'telc.myProgress': 'My Progress',
    'telc.startExam': 'Start Mock Exam',
    'telc.startPractice': 'Start Practice',
    'telc.showAll': 'Show All',
    'telc.passingScore': 'Passing Score',
    'telc.maxPoints': 'Max Points',
    'telc.totalDuration': 'Total Duration',
    'telc.examParts': 'Exam Parts',
    'telc.progress': 'Progress',
    'telc.points': 'points',
    'telc.minutes': 'minutes',
    'telc.parts': 'parts',
    'telc.exercises': 'Exercises',
    'telc.days': 'Days',
    'telc.overview': 'Overview',
    'telc.practice': 'Practice',
    'telc.aiCoach': 'AI Coach',
    'telc.getHint': 'Get Hint',
    'telc.explain': 'Explain',
    'telc.getFeedback': 'Get Feedback',
    'telc.submit': 'Submit',
    'telc.next': 'Next',
    'telc.previous': 'Previous',
    'telc.back': 'Back',
    'telc.startTimer': 'Start Timer',
    'telc.transcript': 'Transcript',
    'telc.playAudio': 'Play Audio',
    'telc.record': 'Record',
    'telc.stopRecording': 'Stop Recording',
    'telc.transcribe': 'Transcribe',
    'telc.question': 'Question',
    'telc.of': 'of',
    
    // Sections
    'telc.section.reading': 'Reading Comprehension',
    'telc.section.listening': 'Listening Comprehension',
    'telc.section.writing': 'Written Expression',
    'telc.section.speaking': 'Oral Expression',
    'telc.section.sprachbausteine': 'Language Elements',
    
    // Stats
    'telc.stats.examsTaken': 'Exams Taken',
    'telc.stats.averageScore': 'Average Score',
    'telc.stats.dayStreak': 'Day Streak 🔥',
    'telc.stats.practiceTime': 'Practice Time',
    'telc.stats.sectionPerformance': 'Section Performance',
    'telc.stats.best': 'Best',
    'telc.stats.focus': 'Focus',
    
    // Grades
    'telc.grade.excellent': 'Excellent',
    'telc.grade.good': 'Good',
    'telc.grade.satisfactory': 'Satisfactory',
    'telc.grade.sufficient': 'Sufficient',
    'telc.grade.failed': 'Not Passed',
    
    // Study Plan
    'telc.studyPlan.todayLearn': 'Learn Today',
    'telc.studyPlan.examDate': 'TELC B2 Exam',
    'telc.studyPlan.dailyGoal': 'Daily Goal',
    'telc.studyPlan.tasksCompleted': 'tasks completed',
    'telc.studyPlan.thisWeek': 'This Week',
    'telc.studyPlan.recommendedExercises': 'Recommended Exercises',
    'telc.studyPlan.mockExam': 'Mock Exam',
    
    // Progress Cards
    'telc.progressCard.advanced': 'Advanced',
    'telc.progressCard.intermediate': 'Intermediate',
    'telc.progressCard.beginner': 'Beginner',
    'telc.progressCard.newStart': 'Start New',
    'telc.progressCard.bestScore': 'Best Score',
    
    // Tips
    'telc.tips.example': 'Example:',
    
    // Audio
    'audio.play': 'Play audio',
    'audio.stop': 'Stop audio',
    'audio.pause': 'Pause',
    'audio.loading': 'Loading audio...',
    
    // Learning German - Always keep visible
    'learningGerman': 'Learning German',
  },
  de: {
    // Navigation  
    'nav.dashboard': 'Dashboard',
    'nav.vocabulary': 'Wortschatz',
    'nav.wordDossier': 'Wort-Dossier',
    'nav.sentence': 'Sätze',
    'nav.writing': 'Schreiben',
    'nav.exercises': 'Übungen',
    'nav.memorizer': 'Memorizer',
    'nav.wordAssociation': 'Wortassoziation',
    'nav.conversation': 'Konversation',
    'nav.highlighter': 'Textmarker',
    'nav.diary': 'Fehlertagebuch',
    'nav.review': 'Wiederholen',
    'nav.activityLog': 'Aktivitätsprotokoll',
    'nav.settings': 'Einstellungen',
    'nav.logout': 'Abmelden',
    'nav.aiCompanion': 'KI-Begleiter',
    'nav.telcExam': 'TELC B2 Prüfung',
    'nav.telcPrep': 'TELC Vorbereitung',
    'nav.history': 'Verlauf & Export',
    'nav.foundations': 'Grundlagen',
    'nav.practice': 'Übung',
    'nav.communication': 'Kommunikation',
    'nav.progress': 'Fortschritt',
    'nav.telcB2': 'TELC B2',
    'nav.learningPath': 'Lernpfad',
    'nav.achievements': 'Erfolge',
    'nav.masteryCourse': 'Meisterkurs',
    'nav.certificates': 'Zertifikate',
    'nav.serverStatus': 'Serverstatus',
    'nav.allSystemsOperational': 'Alle Systeme betriebsbereit',
    'nav.performanceDegraded': 'Leistung beeinträchtigt',
    'nav.serviceUnavailable': 'Service nicht verfügbar',
    'nav.database': 'Datenbank',
    'nav.apiLatency': 'API-Latenz',
    'nav.authService': 'Auth-Service',
    'nav.online': 'Online',
    'nav.down': 'Offline',
    'nav.active': 'Aktiv',
    'nav.lastChecked': 'Zuletzt geprüft',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Willkommen zurück',
    'dashboard.subtitle': 'Setze deine Deutschlernreise fort. Verfolge deinen Fortschritt und schalte neue Erfolge frei.',
    'dashboard.wordsLearned': 'Gelernte Wörter',
    'dashboard.exercisesDone': 'Erledigte Übungen',
    'dashboard.currentStreak': 'Aktuelle Serie',
    'dashboard.totalMistakes': 'Gesamte Fehler',
    'dashboard.weeklyActivity': 'Wöchentliche Aktivität',
    'dashboard.weakSpots': 'Bereiche mit Verbesserungspotenzial',
    'dashboard.recommendations': 'Empfohlene nächste Schritte',
    'dashboard.mistakeDistribution': 'Fehlerverteilung',
    'dashboard.keepGoing': '🔥 Weiter so!',
    'dashboard.learningOpportunities': 'Lernmöglichkeiten',
    'dashboard.noWeakSpots': 'Noch keine Schwachstellen identifiziert. Üben Sie weiter!',
    'dashboard.goal': 'Ziel',
    'dashboard.words': 'Wörter',
    'dashboard.exercises': 'Übungen',
    'dashboard.errors': 'Fehler',
    'dashboard.aiInsights': 'KI-Einblicke',
    'dashboard.generating': 'Generiere Einblicke...',
    'dashboard.quickActions': 'Schnellaktionen',
    
    // Server Status
    'server.healthy': 'Alle Systeme betriebsbereit',
    'server.degraded': 'Eingeschränkte Leistung',
    'server.down': 'System ausgefallen',
    
    // Theme
    'theme.light': 'Heller Modus',
    'theme.dark': 'Dunkler Modus',
    
    // Common
    'common.loading': 'Lädt...',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    'common.cancel': 'Abbrechen',
    'common.save': 'Speichern',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.back': 'Zurück',
    'common.next': 'Weiter',
    'common.previous': 'Zurück',
    'common.submit': 'Absenden',
    'common.close': 'Schließen',
    'common.send': 'Senden',
    'common.retry': 'Erneut versuchen',
    'common.confirm': 'Bestätigen',
    'common.noData': 'Keine Daten verfügbar',
    'common.searchPlaceholder': 'Suchen...',
    'common.days': 'Tage',
    'common.hours': 'Stunden',
    'common.minutes': 'Minuten',
    'common.seconds': 'Sekunden',
    'common.points': 'Punkte',
    'common.level': 'Level',
    'common.xp': 'XP',
    'common.streak': 'Serie',
    'common.startNow': 'Jetzt starten',
    'common.viewAll': 'Alle anzeigen',
    'common.learnMore': 'Mehr erfahren',
    
    // Toast messages
    'toast.saved': 'Erfolgreich gespeichert',
    'toast.deleted': 'Erfolgreich gelöscht',
    'toast.error': 'Etwas ist schiefgelaufen',
    'toast.pleaseLogin': 'Bitte zuerst anmelden',
    'toast.copied': 'In Zwischenablage kopiert',
    'toast.added': 'Erfolgreich hinzugefügt',
    'toast.updated': 'Erfolgreich aktualisiert',
    'toast.generating': 'Wird generiert...',
    'toast.analyzing': 'Wird analysiert...',
    
    // Empty states
    'empty.noResults': 'Keine Ergebnisse gefunden',
    'empty.noItems': 'Noch keine Einträge',
    'empty.startPracticing': 'Beginne zu üben, um deinen Fortschritt zu sehen!',
    'empty.noMistakes': 'Keine Fehler gefunden - weiter üben!',
    'empty.noCertificates': 'Schließe Module ab, um Zertifikate zu erhalten',
    'empty.noAchievements': 'Beginne zu lernen, um Erfolge freizuschalten',
    
    // Auth
    'auth.signIn': 'Anmelden',
    'auth.signUp': 'Registrieren',
    'auth.signOut': 'Abmelden',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.forgotPassword': 'Passwort vergessen?',
    'auth.noAccount': 'Noch kein Konto?',
    'auth.haveAccount': 'Bereits ein Konto?',
    'auth.signInToFluentPass': 'Bei FluentPass anmelden',
    'auth.createFreeAccount': 'Kostenloses Konto erstellen',
    'auth.processing': 'Wird verarbeitet...',
    
    // Sentence Generator
    'sentence.title': 'Satzgenerator',
    'sentence.subtitle': 'Generiere deutsche Sätze zum Üben',
    'sentence.difficulty': 'Schwierigkeitsgrad',
    'sentence.topic': 'Thema (optional)',
    'sentence.topicPlaceholder': 'Thema auswählen oder leer lassen',
    'sentence.noTopic': 'Kein bestimmtes Thema',
    'sentence.customTopic': 'Benutzerdefiniertes Thema...',
    'sentence.customTopicPlaceholder': 'Eigenes Thema eingeben...',
    'sentence.grammarFocus': 'Grammatik-Fokus (optional)',
    'sentence.grammarPlaceholder': 'Grammatikpunkt auswählen oder leer lassen',
    'sentence.noGrammar': 'Keine bestimmte Grammatik',
    'sentence.generate': 'Satz generieren',
    'sentence.generating': 'Wird generiert...',
    'sentence.german': 'Deutsch',
    'sentence.english': 'Englisch',
    'sentence.analysis': 'Grammatikalische Analyse',
    'sentence.generated': 'Satz generiert!',
    
    // Word Dossier
    'word.title': 'Wort-Dossier',
    'word.subtitle': 'Tiefgehende Analyse deutscher Wörter mit Synonymen, Antonymen und Beispielen',
    'word.search': 'Geben Sie ein deutsches Wort zur Analyse ein...',
    'word.analyze': 'Analysieren',
    'word.analyzing': 'Wird analysiert...',
    'word.definition': 'Definition',
    'word.translation': 'Übersetzung',
    'word.wordFamily': 'Wortfamilie',
    'word.prefixVerbs': 'Präfixverben',
    'word.synonyms': 'Synonyme',
    'word.antonyms': 'Antonyme',
    'word.examples': 'Beispielsätze',
    
    // Vocabulary
    'vocabulary.title': 'Vokabel-Generator',
    'vocabulary.subtitle': 'Generiere TELC B2-Vokabeln nach Thema',
    'vocabulary.topic': 'Thema',
    'vocabulary.customTopic': 'Benutzerdefiniertes Thema',
    'vocabulary.numberOfWords': 'Anzahl der Wörter',
    'vocabulary.generate': 'Vokabeln generieren',
    'vocabulary.addToReview': 'Zur Wiederholung hinzufügen',
    'vocabulary.added': 'Zur Wiederholung hinzugefügt!',
    
    // Exercises
    'exercises.title': 'Übungen',
    'exercises.subtitle': 'Übe mit Multiple-Choice, Übersetzung und Lückentexten',
    'exercises.quiz': 'Multiple Choice',
    'exercises.translation': 'Übersetzung',
    'exercises.gapFill': 'Lückentext',
    'exercises.generate': 'Übung generieren',
    'exercises.checkAnswer': 'Antwort prüfen',
    'exercises.nextExercise': 'Nächste Übung',
    'exercises.correct': 'Richtig!',
    'exercises.incorrect': 'Falsch',
    'exercises.yourAnswer': 'Deine Antwort',
    'exercises.correctAnswer': 'Richtige Antwort',
    
    // Writing Assistant
    'writing.title': 'KI-Schreibassistent',
    'writing.subtitle': 'Erhalte B2-C1 Feedback zu deinem Deutsch',
    'writing.prompt': 'Schreibaufgabe',
    'writing.selectPrompt': 'Aufgabe auswählen',
    'writing.analyze': 'Text analysieren',
    'writing.analyzing': 'Wird analysiert...',
    'writing.wordCount': 'Wörter',
    'writing.overallFeedback': 'Gesamtfeedback',
    'writing.correctedText': 'Korrigierter Text',
    'writing.errors': 'Gefundene Fehler',
    'writing.noErrors': 'Keine wesentlichen Fehler gefunden',
    
    // Memorizer
    'memorizer.title': 'Der Memorizer',
    'memorizer.subtitle': 'Generiere deutsche Absätze zum Auswendiglernen',
    'memorizer.theme': 'Thema',
    'memorizer.selectTheme': 'Thema auswählen',
    'memorizer.customTheme': 'Eigenes Thema...',
    'memorizer.generate': 'Absatz generieren',
    'memorizer.addToReview': 'Zur Wiederholung hinzufügen',
    'memorizer.practice': 'Schreiben üben',
    'memorizer.showAnswer': 'Antwort zeigen',
    'memorizer.hideAnswer': 'Antwort verbergen',
    'memorizer.accuracy': 'Genauigkeit',
    
    // Word Association
    'wordAssociation.title': 'Wortassoziation',
    'wordAssociation.subtitle': 'Teste deinen Wortschatz mit KI-generierten Wortassoziationen',
    'wordAssociation.startGame': 'Spiel starten',
    'wordAssociation.endGame': 'Spiel beenden',
    'wordAssociation.score': 'Punkte',
    'wordAssociation.round': 'Runde',
    'wordAssociation.hint': 'Hinweis',
    'wordAssociation.saveWord': 'Wort speichern',
    'wordAssociation.explain': 'Erklären',
    
    // Conversation
    'conversation.title': 'Konversationsübung',
    'conversation.subtitle': 'Übe realistische deutsche Gespräche mit KI',
    'conversation.scenario': 'Szenario',
    'conversation.selectScenario': 'Szenario auswählen',
    'conversation.startConversation': 'Gespräch starten',
    'conversation.endConversation': 'Gespräch beenden',
    'conversation.textMode': 'Textmodus',
    'conversation.voiceMode': 'Sprachmodus',
    'conversation.analyzing': 'Wird analysiert...',
    'conversation.translate': 'Übersetzen',
    
    // Text Highlighter
    'highlighter.title': 'Textmarker',
    'highlighter.subtitle': 'Füge deutschen Text ein und markiere Vokabeln auf deinem Niveau',
    'highlighter.paste': 'Deutschen Text einfügen (z.B. Nachrichtenartikel)',
    'highlighter.analyze': 'Markieren',
    'highlighter.addToReview': 'Zur Wiederholung hinzufügen',
    'highlighter.wordDetails': 'Wortdetails',
    'highlighter.vocabularyList': 'Vokabelliste',
    
    // Mistake Diary
    'diary.title': 'Fehlertagebuch',
    'diary.subtitle': 'Verfolge und lerne aus deinen Fehlern',
    'diary.exportPDF': 'PDF exportieren',
    'diary.openNewTab': 'In neuem Tab öffnen',
    'diary.totalMistakes': 'Gesamte Fehler',
    'diary.resolved': 'Gelöst',
    'diary.active': 'Aktiv',
    'diary.categories': 'Kategorien',
    'diary.completion': 'Abschluss',
    'diary.search': 'Fehler suchen...',
    'diary.showAll': 'Alle anzeigen',
    'diary.showResolved': 'Gelöste anzeigen',
    'diary.all': 'Alle',
    'diary.listView': 'Listenansicht',
    'diary.analytics': 'Analytik',
    'diary.noMistakes': 'Keine Fehler gefunden',
    'diary.tryAdjusting': 'Versuche die Suche anzupassen',
    'diary.keepPracticing': 'Übe weiter, um deinen Fortschritt zu verfolgen!',
    'diary.yourText': 'Dein Text:',
    'diary.correction': 'Korrektur:',
    'diary.explanation': 'Erklärung:',
    'diary.context': 'Kontext:',
    'diary.addNote': 'Notiz hinzufügen',
    'diary.editNote': 'Notiz bearbeiten',
    'diary.saveNote': 'Notiz speichern',
    'diary.notePlaceholder': 'Füge persönliche Notizen zu diesem Fehler hinzu...',
    'diary.markResolved': 'Fehler als gelöst markiert',
    'diary.markUnresolved': 'Als ungelöst markiert',
    'diary.mistakesByType': 'Fehler nach Typ',
    'diary.mistakesByCategory': 'Fehler nach Kategorie',
    'diary.autoDetecting': 'Automatische Fehlererkennung...',
    'diary.autoDetect': 'Auto-Erkennung',
    'diary.mistakeDeleted': 'Fehler erfolgreich gelöscht',
    'diary.deleteFailed': 'Fehler beim Löschen',
    'diary.noContentFound': 'Kein Inhalt zum Analysieren',
    'diary.completeExercises': 'Zuerst einige Übungen abschließen',
    'diary.detected': 'Erkannt',
    'diary.newMistakes': 'neue(r) Fehler',
    'diary.noNewMistakes': 'Keine neuen Fehler erkannt',
    'diary.greatJob': 'Gute Arbeit! Weiter üben!',
    'diary.autoDetectFailed': 'Automatische Fehlererkennung fehlgeschlagen',
    
    // Review
    'review.title': 'Wiederholen',
    'review.subtitle': 'Vokabeln mit Spaced Repetition wiederholen',
    'review.dueItems': 'Fällige Einträge',
    'review.showAnswer': 'Antwort zeigen',
    'review.knewIt': 'Gewusst',
    'review.needsPractice': 'Muss üben',
    'review.noItems': 'Keine Einträge zur Wiederholung fällig',
    'review.complete': 'Wiederholung abgeschlossen!',
    
    // Settings
    'settings.title': 'Einstellungen',
    'settings.account': 'Kontoinformationen',
    'settings.email': 'E-Mail',
    'settings.userId': 'Benutzer-ID',
    'settings.apiKeys': 'API-Schlüssel',
    'settings.preferences': 'Einstellungen',
    'settings.audioPlayback': 'Audio-Wiedergabe',
    'settings.reviewReminders': 'Wiederholungserinnerungen',
    'settings.savePreferences': 'Einstellungen speichern',
    'settings.dangerZone': 'Gefahrenzone',
    'settings.deleteAccount': 'Konto löschen',
    'settings.subscription': 'Abonnement',
    'settings.manageSubscription': 'Abonnement verwalten',
    'settings.viewPlans': 'Pläne ansehen',
    'settings.studyStats': 'Lernstatistiken',
    'settings.accountCreated': 'Konto erstellt',
    'settings.lastLogin': 'Letzte Anmeldung',
    
    // AI Companion
    'aiCompanion.title': 'KI-Lernbegleiter',
    'aiCompanion.subtitle': 'Dein persönlicher Deutschtutor, der sich an dein Niveau anpasst',
    'aiCompanion.startConversation': 'Gespräch starten',
    'aiCompanion.starting': 'Wird gestartet...',
    'aiCompanion.listening': 'Höre zu...',
    'aiCompanion.processing': 'Verarbeitung...',
    'aiCompanion.textMode': 'Textmodus',
    'aiCompanion.verbalMode': 'Sprachmodus',
    'aiCompanion.analyzeMistakes': 'Fehler analysieren',
    'aiCompanion.achievements': 'Erfolge',
    'aiCompanion.aiInsights': 'KI-Einblicke',
    'aiCompanion.learningStyle': 'Lernstil',
    'aiCompanion.strength': 'Stärke',
    'aiCompanion.focusArea': 'Fokusbereich',
    'aiCompanion.instantFeedback': 'Sofortiges Feedback',
    'aiCompanion.placeholder': 'Auf Deutsch tippen oder Sprache verwenden...',
    'aiCompanion.voice': 'Sprache',
    'aiCompanion.stop': 'Stopp',
    'aiCompanion.mistakeAnalysis': 'Fehleranalyse & Vorschläge',
    'aiCompanion.noErrors': 'Ausgezeichnet! Keine wesentlichen Fehler gefunden.',
    'aiCompanion.mistakesFound': 'Gefundene Fehler',
    'aiCompanion.alternatives': 'Alternative Formulierungen',
    'aiCompanion.overallAssessment': 'Gesamtbewertung',
    'aiCompanion.recentAchievements': 'Aktuelle Erfolge',
    'aiCompanion.startChatting': 'Beginne zu chatten, um freizuschalten!',
    
    // Subscriptions
    'subscriptions.title': 'Wähle deinen Plan',
    'subscriptions.subtitle': 'Entfalte dein volles Potenzial mit FluentPass Premium',
    'subscriptions.currentPlan': 'Aktueller Plan',
    'subscriptions.upgradeNow': 'Jetzt upgraden',
    'subscriptions.perMonth': '/Monat',
    'subscriptions.popular': 'Beliebteste',
    'subscriptions.features': 'Das bekommst du:',
    
    // Learning Path
    'learningPath.title': 'Dein Lernpfad',
    'learningPath.subtitle': 'KI-gesteuerter Lehrplan für deine TELC B2 Zertifizierung',
    'learningPath.createPath': 'Lernpfad erstellen',
    'learningPath.generateLesson': 'Heutige Lektion generieren',
    'learningPath.dailyLesson': 'Heutige Lektion',
    'learningPath.completed': 'Abgeschlossen',
    'learningPath.tasks': 'Aufgaben',
    
    // Achievements
    'achievements.title': 'Erfolge',
    'achievements.subtitle': 'Schalte Erfolge frei, während du Deutsch lernst',
    'achievements.totalXP': 'Gesamt-XP',
    'achievements.unlocked': 'Freigeschaltet',
    'achievements.checkAchievements': 'Erfolge prüfen',
    'achievements.checking': 'Wird geprüft...',
    
    // Mastery Course
    'masteryCourse.title': 'FluentPass Meisterkurs',
    'masteryCourse.subtitle': 'Umfassendes 12-Wochen-Programm für die TELC B2 Zertifizierung',
    'masteryCourse.modules': 'Module',
    'masteryCourse.overview': 'Übersicht',
    'masteryCourse.progress': 'Kursfortschritt',
    'masteryCourse.completed': 'abgeschlossen',
    'masteryCourse.getCertificate': 'Kurszertifikat erhalten',
    
    // Certificates
    'certificates.title': 'Meine Zertifikate',
    'certificates.subtitle': 'Deine erworbenen Zertifikate aus dem FluentPass Meisterkurs',
    'certificates.download': 'Herunterladen',
    'certificates.share': 'Teilen',
    'certificates.noCertificates': 'Noch keine Zertifikate',
    'certificates.startCourse': 'Starte den Meisterkurs, um Zertifikate zu erhalten',
    'certificates.howToEarn': 'So erhältst du Zertifikate',
    
    // History
    'history.title': 'Lernverlauf',
    'history.subtitle': 'Zeige und exportiere deinen Lernfortschritt',
    'history.exportAll': 'Alles exportieren',
    'history.vocabulary': 'Vokabeln',
    'history.exercises': 'Übungen',
    'history.writing': 'Schreiben',
    'history.conversations': 'Gespräche',
    'history.mistakes': 'Fehler',
    'history.memorizer': 'Memorizer',
    
    // TELC B2 Preparation
    'telc.title': 'TELC B2 Prüfungsvorbereitung',
    'telc.subtitle': 'Bereite dich optimal auf deine TELC B2 Prüfung vor',
    'telc.examSections': 'Prüfungsbereiche',
    'telc.myProgress': 'Mein Fortschritt',
    'telc.startExam': 'Probeklausur starten',
    'telc.startPractice': 'Übungen starten',
    'telc.showAll': 'Alle anzeigen',
    'telc.passingScore': 'Bestehensgrenze',
    'telc.maxPoints': 'Maximalpunkte',
    'telc.totalDuration': 'Gesamtdauer',
    'telc.examParts': 'Prüfungsteile',
    'telc.progress': 'Fortschritt',
    'telc.points': 'Punkte',
    'telc.minutes': 'Minuten',
    'telc.parts': 'Teile',
    'telc.exercises': 'Übungen',
    'telc.days': 'Tage',
    'telc.overview': 'Übersicht',
    'telc.practice': 'Üben',
    'telc.aiCoach': 'KI-Coach',
    'telc.getHint': 'Hinweis',
    'telc.explain': 'Erklären',
    'telc.getFeedback': 'Feedback',
    'telc.submit': 'Absenden',
    'telc.next': 'Weiter',
    'telc.previous': 'Zurück',
    'telc.back': 'Zurück',
    'telc.startTimer': 'Timer starten',
    'telc.transcript': 'Transkript',
    'telc.playAudio': 'Audio abspielen',
    'telc.record': 'Aufnehmen',
    'telc.stopRecording': 'Aufnahme beenden',
    'telc.transcribe': 'Transkribieren',
    'telc.question': 'Frage',
    'telc.of': 'von',
    
    // Sections
    'telc.section.reading': 'Leseverstehen',
    'telc.section.listening': 'Hörverstehen',
    'telc.section.writing': 'Schriftlicher Ausdruck',
    'telc.section.speaking': 'Mündlicher Ausdruck',
    'telc.section.sprachbausteine': 'Sprachbausteine',
    
    // Stats
    'telc.stats.examsTaken': 'Prüfungen absolviert',
    'telc.stats.averageScore': 'Durchschnitt',
    'telc.stats.dayStreak': 'Tage-Serie 🔥',
    'telc.stats.practiceTime': 'Übungszeit',
    'telc.stats.sectionPerformance': 'Bereichsleistung',
    'telc.stats.best': 'Beste',
    'telc.stats.focus': 'Fokus',
    
    // Grades
    'telc.grade.excellent': 'Sehr gut',
    'telc.grade.good': 'Gut',
    'telc.grade.satisfactory': 'Befriedigend',
    'telc.grade.sufficient': 'Ausreichend',
    'telc.grade.failed': 'Nicht bestanden',
    
    // Study Plan
    'telc.studyPlan.todayLearn': 'Heute lernen',
    'telc.studyPlan.examDate': 'TELC B2 Prüfung',
    'telc.studyPlan.dailyGoal': 'Tagesziel',
    'telc.studyPlan.tasksCompleted': 'Aufgaben erledigt',
    'telc.studyPlan.thisWeek': 'Diese Woche',
    'telc.studyPlan.recommendedExercises': 'Empfohlene Übungen',
    'telc.studyPlan.mockExam': 'Probeklausur',
    
    // Progress Cards
    'telc.progressCard.advanced': 'Fortgeschritten',
    'telc.progressCard.intermediate': 'Gut',
    'telc.progressCard.beginner': 'Anfänger',
    'telc.progressCard.newStart': 'Neu starten',
    'telc.progressCard.bestScore': 'Beste Note',
    
    // Tips
    'telc.tips.example': 'Beispiel:',
    
    // Audio
    'audio.play': 'Audio abspielen',
    'audio.stop': 'Audio stoppen',
    'audio.pause': 'Pause',
    'audio.loading': 'Audio lädt...',
    
    // Learning German - Always keep visible
    'learningGerman': 'Deutsch lernen',
  },
  ar: {
    // Navigation  
    'nav.dashboard': 'لوحة التحكم',
    'nav.vocabulary': 'المفردات',
    'nav.wordDossier': 'ملف الكلمات',
    'nav.sentence': 'الجمل',
    'nav.writing': 'الكتابة',
    'nav.exercises': 'التمارين',
    'nav.memorizer': 'الحفظ',
    'nav.wordAssociation': 'ربط الكلمات',
    'nav.conversation': 'المحادثة',
    'nav.highlighter': 'التظليل',
    'nav.diary': 'يومية الأخطاء',
    'nav.review': 'المراجعة',
    'nav.activityLog': 'سجل النشاط',
    'nav.settings': 'الإعدادات',
    'nav.logout': 'تسجيل الخروج',
    'nav.aiCompanion': 'رفيق الذكاء الاصطناعي',
    'nav.telcExam': 'امتحان TELC B2',
    'nav.telcPrep': 'تحضير TELC',
    'nav.history': 'السجل والتصدير',
    'nav.foundations': 'الأساسيات',
    'nav.practice': 'التدريب',
    'nav.communication': 'التواصل',
    'nav.progress': 'التقدم',
    'nav.telcB2': 'TELC B2',
    'nav.learningPath': 'مسار التعلم',
    'nav.achievements': 'الإنجازات',
    'nav.masteryCourse': 'دورة الإتقان',
    'nav.certificates': 'الشهادات',
    'nav.serverStatus': 'حالة الخادم',
    'nav.allSystemsOperational': 'جميع الأنظمة تعمل',
    'nav.performanceDegraded': 'الأداء منخفض',
    'nav.serviceUnavailable': 'الخدمة غير متاحة',
    'nav.database': 'قاعدة البيانات',
    'nav.apiLatency': 'وقت استجابة API',
    'nav.authService': 'خدمة المصادقة',
    'nav.online': 'متصل',
    'nav.down': 'معطل',
    'nav.active': 'نشط',
    'nav.lastChecked': 'آخر فحص',
    
    // Dashboard
    'dashboard.title': 'لوحة التحكم',
    'dashboard.welcome': 'مرحباً بعودتك',
    'dashboard.subtitle': 'تابع رحلة تعلم الألمانية. تتبع تقدمك واكتشف إنجازات جديدة.',
    'dashboard.wordsLearned': 'الكلمات المتعلمة',
    'dashboard.exercisesDone': 'التمارين المنجزة',
    'dashboard.currentStreak': 'السلسلة الحالية',
    'dashboard.totalMistakes': 'إجمالي الأخطاء',
    'dashboard.weeklyActivity': 'النشاط الأسبوعي',
    'dashboard.weakSpots': 'المجالات التي تحتاج تركيز',
    'dashboard.recommendations': 'الخطوات التالية الموصى بها',
    'dashboard.mistakeDistribution': 'توزيع الأخطاء',
    'dashboard.keepGoing': '🔥 استمر!',
    'dashboard.learningOpportunities': 'فرص التعلم',
    'dashboard.noWeakSpots': 'لم يتم تحديد نقاط ضعف بعد. استمر في الممارسة!',
    'dashboard.goal': 'الهدف',
    'dashboard.words': 'كلمات',
    'dashboard.exercises': 'تمارين',
    'dashboard.errors': 'أخطاء',
    'dashboard.aiInsights': 'رؤى الذكاء الاصطناعي',
    'dashboard.generating': 'جاري توليد الرؤى...',
    'dashboard.quickActions': 'إجراءات سريعة',
    
    // Server Status
    'server.healthy': 'جميع الأنظمة تعمل',
    'server.degraded': 'أداء منخفض',
    'server.down': 'النظام معطل',
    
    // Theme
    'theme.light': 'الوضع الفاتح',
    'theme.dark': 'الوضع الداكن',
    
    // Common
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجاح',
    'common.cancel': 'إلغاء',
    'common.save': 'حفظ',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.submit': 'إرسال',
    'common.close': 'إغلاق',
    'common.send': 'إرسال',
    'common.retry': 'إعادة المحاولة',
    'common.confirm': 'تأكيد',
    'common.noData': 'لا توجد بيانات',
    'common.searchPlaceholder': 'بحث...',
    'common.days': 'أيام',
    'common.hours': 'ساعات',
    'common.minutes': 'دقائق',
    'common.seconds': 'ثواني',
    'common.points': 'نقاط',
    'common.level': 'المستوى',
    'common.xp': 'XP',
    'common.streak': 'سلسلة',
    'common.startNow': 'ابدأ الآن',
    'common.viewAll': 'عرض الكل',
    'common.learnMore': 'اعرف المزيد',
    
    // Toast messages
    'toast.saved': 'تم الحفظ بنجاح',
    'toast.deleted': 'تم الحذف بنجاح',
    'toast.error': 'حدث خطأ ما',
    'toast.pleaseLogin': 'يرجى تسجيل الدخول أولاً',
    'toast.copied': 'تم النسخ إلى الحافظة',
    'toast.added': 'تمت الإضافة بنجاح',
    'toast.updated': 'تم التحديث بنجاح',
    'toast.generating': 'جاري التوليد...',
    'toast.analyzing': 'جاري التحليل...',
    
    // Empty states
    'empty.noResults': 'لا توجد نتائج',
    'empty.noItems': 'لا توجد عناصر بعد',
    'empty.startPracticing': 'ابدأ التمرين لرؤية تقدمك!',
    'empty.noMistakes': 'لا توجد أخطاء - استمر في التمرين!',
    'empty.noCertificates': 'أكمل الوحدات للحصول على الشهادات',
    'empty.noAchievements': 'ابدأ التعلم لفتح الإنجازات',
    
    // Auth
    'auth.signIn': 'تسجيل الدخول',
    'auth.signUp': 'إنشاء حساب',
    'auth.signOut': 'تسجيل الخروج',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.noAccount': 'ليس لديك حساب؟',
    'auth.haveAccount': 'لديك حساب بالفعل؟',
    'auth.signInToFluentPass': 'تسجيل الدخول إلى FluentPass',
    'auth.createFreeAccount': 'إنشاء حساب مجاني',
    'auth.processing': 'جاري المعالجة...',
    
    // Sentence Generator
    'sentence.title': 'مولد الجمل',
    'sentence.subtitle': 'أنشئ جملاً ألمانية للتمرين',
    'sentence.difficulty': 'مستوى الصعوبة',
    'sentence.topic': 'الموضوع (اختياري)',
    'sentence.topicPlaceholder': 'اختر موضوعاً أو اتركه فارغاً',
    'sentence.noTopic': 'لا يوجد موضوع محدد',
    'sentence.customTopic': 'موضوع مخصص...',
    'sentence.customTopicPlaceholder': 'أدخل موضوعك...',
    'sentence.grammarFocus': 'التركيز النحوي (اختياري)',
    'sentence.grammarPlaceholder': 'اختر نقطة نحوية أو اتركها فارغة',
    'sentence.noGrammar': 'لا توجد قواعد محددة',
    'sentence.generate': 'إنشاء جملة',
    'sentence.generating': 'جاري الإنشاء...',
    'sentence.german': 'الألمانية',
    'sentence.english': 'الإنجليزية',
    'sentence.analysis': 'التحليل النحوي',
    'sentence.generated': 'تم إنشاء الجملة!',
    
    // Word Dossier
    'word.title': 'ملف الكلمة',
    'word.subtitle': 'تحليل عميق للكلمات الألمانية مع المرادفات والأضداد',
    'word.search': 'أدخل كلمة ألمانية للتحليل...',
    'word.analyze': 'تحليل',
    'word.analyzing': 'جاري التحليل...',
    'word.definition': 'التعريف',
    'word.translation': 'الترجمة',
    'word.wordFamily': 'عائلة الكلمة',
    'word.prefixVerbs': 'أفعال البادئة',
    'word.synonyms': 'المرادفات',
    'word.antonyms': 'الأضداد',
    'word.examples': 'جمل مثالية',
    
    // Vocabulary
    'vocabulary.title': 'مولد المفردات',
    'vocabulary.subtitle': 'أنشئ مفردات TELC B2 حسب الموضوع',
    'vocabulary.topic': 'الموضوع',
    'vocabulary.customTopic': 'موضوع مخصص',
    'vocabulary.numberOfWords': 'عدد الكلمات',
    'vocabulary.generate': 'توليد المفردات',
    'vocabulary.addToReview': 'إضافة للمراجعة',
    'vocabulary.added': 'تمت الإضافة للمراجعة!',
    
    // Exercises
    'exercises.title': 'التمارين',
    'exercises.subtitle': 'تمرن على الاختيار المتعدد والترجمة وملء الفراغات',
    'exercises.quiz': 'اختيار متعدد',
    'exercises.translation': 'ترجمة',
    'exercises.gapFill': 'ملء الفراغات',
    'exercises.generate': 'إنشاء تمرين',
    'exercises.checkAnswer': 'تحقق من الإجابة',
    'exercises.nextExercise': 'التمرين التالي',
    'exercises.correct': 'صحيح!',
    'exercises.incorrect': 'خطأ',
    'exercises.yourAnswer': 'إجابتك',
    'exercises.correctAnswer': 'الإجابة الصحيحة',
    
    // Writing Assistant
    'writing.title': 'مساعد الكتابة بالذكاء الاصطناعي',
    'writing.subtitle': 'احصل على ملاحظات B2-C1 على كتابتك الألمانية',
    'writing.prompt': 'موضوع الكتابة',
    'writing.selectPrompt': 'اختر موضوعاً',
    'writing.analyze': 'تحليل النص',
    'writing.analyzing': 'جاري التحليل...',
    'writing.wordCount': 'كلمات',
    'writing.overallFeedback': 'الملاحظات العامة',
    'writing.correctedText': 'النص المصحح',
    'writing.errors': 'الأخطاء الموجودة',
    'writing.noErrors': 'لا توجد أخطاء كبيرة',
    
    // Memorizer
    'memorizer.title': 'المحفظ',
    'memorizer.subtitle': 'أنشئ فقرات ألمانية للحفظ والتمرين',
    'memorizer.theme': 'الموضوع',
    'memorizer.selectTheme': 'اختر موضوعاً',
    'memorizer.customTheme': 'موضوع مخصص...',
    'memorizer.generate': 'إنشاء فقرة',
    'memorizer.addToReview': 'إضافة للمراجعة',
    'memorizer.practice': 'تمرين الكتابة',
    'memorizer.showAnswer': 'إظهار الإجابة',
    'memorizer.hideAnswer': 'إخفاء الإجابة',
    'memorizer.accuracy': 'الدقة',
    
    // Word Association
    'wordAssociation.title': 'ربط الكلمات',
    'wordAssociation.subtitle': 'اختبر مفرداتك مع روابط الكلمات المولدة بالذكاء الاصطناعي',
    'wordAssociation.startGame': 'بدء اللعبة',
    'wordAssociation.endGame': 'إنهاء اللعبة',
    'wordAssociation.score': 'النقاط',
    'wordAssociation.round': 'الجولة',
    'wordAssociation.hint': 'تلميح',
    'wordAssociation.saveWord': 'حفظ الكلمة',
    'wordAssociation.explain': 'شرح',
    
    // Conversation
    'conversation.title': 'تمرين المحادثة',
    'conversation.subtitle': 'تمرن على المحادثات الألمانية مع الذكاء الاصطناعي',
    'conversation.scenario': 'السيناريو',
    'conversation.selectScenario': 'اختر سيناريو',
    'conversation.startConversation': 'بدء المحادثة',
    'conversation.endConversation': 'إنهاء المحادثة',
    'conversation.textMode': 'وضع النص',
    'conversation.voiceMode': 'وضع الصوت',
    'conversation.analyzing': 'جاري التحليل...',
    'conversation.translate': 'ترجمة',
    
    // Text Highlighter
    'highlighter.title': 'تظليل النص',
    'highlighter.subtitle': 'الصق نصاً ألمانياً وظلل المفردات على مستواك',
    'highlighter.paste': 'الصق نصاً ألمانياً (مثل مقال إخباري)',
    'highlighter.analyze': 'تظليل',
    'highlighter.addToReview': 'إضافة للمراجعة',
    'highlighter.wordDetails': 'تفاصيل الكلمة',
    'highlighter.vocabularyList': 'قائمة المفردات',
    
    // Mistake Diary
    'diary.title': 'يومية الأخطاء',
    'diary.subtitle': 'تتبع وتعلم من أخطائك',
    'diary.exportPDF': 'تصدير PDF',
    'diary.openNewTab': 'فتح في علامة تبويب جديدة',
    'diary.totalMistakes': 'إجمالي الأخطاء',
    'diary.resolved': 'تم الحل',
    'diary.active': 'نشط',
    'diary.categories': 'الفئات',
    'diary.completion': 'الإكمال',
    'diary.search': 'البحث عن الأخطاء...',
    'diary.showAll': 'إظهار الكل',
    'diary.showResolved': 'إظهار المحلول',
    'diary.all': 'الكل',
    'diary.listView': 'عرض القائمة',
    'diary.analytics': 'التحليلات',
    'diary.noMistakes': 'لا توجد أخطاء',
    'diary.tryAdjusting': 'حاول تعديل بحثك',
    'diary.keepPracticing': 'استمر في التمرين لتتبع تقدمك!',
    'diary.yourText': 'نصك:',
    'diary.correction': 'التصحيح:',
    'diary.explanation': 'الشرح:',
    'diary.context': 'السياق:',
    'diary.addNote': 'إضافة ملاحظة',
    'diary.editNote': 'تحرير الملاحظة',
    'diary.saveNote': 'حفظ الملاحظة',
    'diary.notePlaceholder': 'أضف ملاحظاتك حول هذا الخطأ...',
    'diary.markResolved': 'تم تحديد الخطأ كمحلول',
    'diary.markUnresolved': 'تحديد كغير محلول',
    'diary.mistakesByType': 'الأخطاء حسب النوع',
    'diary.mistakesByCategory': 'الأخطاء حسب الفئة',
    'diary.autoDetecting': 'الكشف التلقائي...',
    'diary.autoDetect': 'الكشف التلقائي',
    'diary.mistakeDeleted': 'تم حذف الخطأ بنجاح',
    'diary.deleteFailed': 'فشل في حذف الخطأ',
    'diary.noContentFound': 'لا يوجد محتوى للتحليل',
    'diary.completeExercises': 'أكمل بعض التمارين أولاً',
    'diary.detected': 'تم الكشف عن',
    'diary.newMistakes': 'خطأ (أخطاء) جديد',
    'diary.noNewMistakes': 'لم يتم الكشف عن أخطاء جديدة',
    'diary.greatJob': 'عمل رائع! استمر!',
    'diary.autoDetectFailed': 'فشل الكشف التلقائي',
    
    // Review
    'review.title': 'المراجعة',
    'review.subtitle': 'راجع المفردات بالتكرار المتباعد',
    'review.dueItems': 'العناصر المستحقة',
    'review.showAnswer': 'إظهار الإجابة',
    'review.knewIt': 'أعرفها',
    'review.needsPractice': 'تحتاج تمرين',
    'review.noItems': 'لا توجد عناصر مستحقة للمراجعة',
    'review.complete': 'اكتملت المراجعة!',
    
    // Settings
    'settings.title': 'الإعدادات',
    'settings.account': 'معلومات الحساب',
    'settings.email': 'البريد الإلكتروني',
    'settings.userId': 'معرف المستخدم',
    'settings.apiKeys': 'مفاتيح API',
    'settings.preferences': 'التفضيلات',
    'settings.audioPlayback': 'تشغيل الصوت',
    'settings.reviewReminders': 'تذكيرات المراجعة',
    'settings.savePreferences': 'حفظ التفضيلات',
    'settings.dangerZone': 'منطقة الخطر',
    'settings.deleteAccount': 'حذف الحساب',
    'settings.subscription': 'الاشتراك',
    'settings.manageSubscription': 'إدارة الاشتراك',
    'settings.viewPlans': 'عرض الخطط',
    'settings.studyStats': 'إحصائيات الدراسة',
    'settings.accountCreated': 'تاريخ إنشاء الحساب',
    'settings.lastLogin': 'آخر تسجيل دخول',
    
    // AI Companion
    'aiCompanion.title': 'رفيق التعلم الذكي',
    'aiCompanion.subtitle': 'معلمك الألماني الشخصي الذي يتكيف مع مستواك',
    'aiCompanion.startConversation': 'بدء المحادثة',
    'aiCompanion.starting': 'جاري البدء...',
    'aiCompanion.listening': 'الاستماع...',
    'aiCompanion.processing': 'جاري المعالجة...',
    'aiCompanion.textMode': 'وضع النص',
    'aiCompanion.verbalMode': 'الوضع الشفهي',
    'aiCompanion.analyzeMistakes': 'تحليل الأخطاء',
    'aiCompanion.achievements': 'الإنجازات',
    'aiCompanion.aiInsights': 'رؤى الذكاء الاصطناعي',
    'aiCompanion.learningStyle': 'نمط التعلم',
    'aiCompanion.strength': 'نقطة القوة',
    'aiCompanion.focusArea': 'منطقة التركيز',
    'aiCompanion.instantFeedback': 'ملاحظات فورية',
    'aiCompanion.placeholder': 'اكتب بالألمانية أو استخدم الصوت...',
    'aiCompanion.voice': 'صوت',
    'aiCompanion.stop': 'إيقاف',
    'aiCompanion.mistakeAnalysis': 'تحليل الأخطاء والاقتراحات',
    'aiCompanion.noErrors': 'ممتاز! لا توجد أخطاء كبيرة.',
    'aiCompanion.mistakesFound': 'الأخطاء الموجودة',
    'aiCompanion.alternatives': 'طرق بديلة للقول',
    'aiCompanion.overallAssessment': 'التقييم العام',
    'aiCompanion.recentAchievements': 'الإنجازات الأخيرة',
    'aiCompanion.startChatting': 'ابدأ المحادثة للفتح!',
    
    // Subscriptions
    'subscriptions.title': 'اختر خطتك',
    'subscriptions.subtitle': 'أطلق إمكاناتك الكاملة مع FluentPass Premium',
    'subscriptions.currentPlan': 'الخطة الحالية',
    'subscriptions.upgradeNow': 'ترقية الآن',
    'subscriptions.perMonth': '/شهرياً',
    'subscriptions.popular': 'الأكثر شعبية',
    'subscriptions.features': 'ما ستحصل عليه:',
    
    // Learning Path
    'learningPath.title': 'مسار التعلم',
    'learningPath.subtitle': 'منهج شخصي بالذكاء الاصطناعي لشهادة TELC B2',
    'learningPath.createPath': 'إنشاء مسار التعلم',
    'learningPath.generateLesson': 'إنشاء درس اليوم',
    'learningPath.dailyLesson': 'درس اليوم',
    'learningPath.completed': 'مكتمل',
    'learningPath.tasks': 'المهام',
    
    // Achievements
    'achievements.title': 'الإنجازات',
    'achievements.subtitle': 'افتح الإنجازات أثناء رحلة تعلم الألمانية',
    'achievements.totalXP': 'إجمالي XP',
    'achievements.unlocked': 'مفتوح',
    'achievements.checkAchievements': 'تحقق من الإنجازات',
    'achievements.checking': 'جاري التحقق...',
    
    // Mastery Course
    'masteryCourse.title': 'دورة إتقان FluentPass',
    'masteryCourse.subtitle': 'برنامج شامل 12 أسبوعاً لشهادة TELC B2',
    'masteryCourse.modules': 'الوحدات',
    'masteryCourse.overview': 'نظرة عامة',
    'masteryCourse.progress': 'تقدم الدورة',
    'masteryCourse.completed': 'مكتمل',
    'masteryCourse.getCertificate': 'احصل على شهادة الدورة',
    
    // Certificates
    'certificates.title': 'شهاداتي',
    'certificates.subtitle': 'شهاداتك المكتسبة من دورة إتقان FluentPass',
    'certificates.download': 'تحميل',
    'certificates.share': 'مشاركة',
    'certificates.noCertificates': 'لا توجد شهادات بعد',
    'certificates.startCourse': 'ابدأ دورة الإتقان للحصول على شهادات',
    'certificates.howToEarn': 'كيفية الحصول على الشهادات',
    
    // History
    'history.title': 'سجل التعلم',
    'history.subtitle': 'عرض وتصدير تقدمك في التعلم',
    'history.exportAll': 'تصدير الكل',
    'history.vocabulary': 'المفردات',
    'history.exercises': 'التمارين',
    'history.writing': 'الكتابة',
    'history.conversations': 'المحادثات',
    'history.mistakes': 'الأخطاء',
    'history.memorizer': 'الحفظ',
    
    // TELC B2 Preparation
    'telc.title': 'التحضير لامتحان TELC B2',
    'telc.subtitle': 'استعد لامتحان TELC B2 مع تمارين تفاعلية وتدريب بالذكاء الاصطناعي',
    'telc.examSections': 'أقسام الامتحان',
    'telc.myProgress': 'تقدمي',
    'telc.startExam': 'بدء الامتحان التجريبي',
    'telc.startPractice': 'بدء التمارين',
    'telc.showAll': 'عرض الكل',
    'telc.passingScore': 'درجة النجاح',
    'telc.maxPoints': 'أقصى النقاط',
    'telc.totalDuration': 'المدة الإجمالية',
    'telc.examParts': 'أقسام الامتحان',
    'telc.progress': 'التقدم',
    'telc.points': 'نقاط',
    'telc.minutes': 'دقائق',
    'telc.parts': 'أجزاء',
    'telc.exercises': 'تمارين',
    'telc.days': 'أيام',
    'telc.overview': 'نظرة عامة',
    'telc.practice': 'تمرين',
    'telc.aiCoach': 'مدرب الذكاء الاصطناعي',
    'telc.getHint': 'تلميح',
    'telc.explain': 'شرح',
    'telc.getFeedback': 'ملاحظات',
    'telc.submit': 'إرسال',
    'telc.next': 'التالي',
    'telc.previous': 'السابق',
    'telc.back': 'رجوع',
    'telc.startTimer': 'بدء المؤقت',
    'telc.transcript': 'النص',
    'telc.playAudio': 'تشغيل الصوت',
    'telc.record': 'تسجيل',
    'telc.stopRecording': 'إيقاف التسجيل',
    'telc.transcribe': 'نسخ',
    'telc.question': 'سؤال',
    'telc.of': 'من',
    
    // Sections
    'telc.section.reading': 'فهم القراءة',
    'telc.section.listening': 'فهم الاستماع',
    'telc.section.writing': 'التعبير الكتابي',
    'telc.section.speaking': 'التعبير الشفهي',
    'telc.section.sprachbausteine': 'العناصر اللغوية',
    
    // Stats
    'telc.stats.examsTaken': 'الامتحانات المؤداة',
    'telc.stats.averageScore': 'متوسط الدرجة',
    'telc.stats.dayStreak': 'أيام متتالية 🔥',
    'telc.stats.practiceTime': 'وقت الممارسة',
    'telc.stats.sectionPerformance': 'أداء الأقسام',
    'telc.stats.best': 'الأفضل',
    'telc.stats.focus': 'التركيز',
    
    // Grades
    'telc.grade.excellent': 'ممتاز',
    'telc.grade.good': 'جيد',
    'telc.grade.satisfactory': 'مقبول',
    'telc.grade.sufficient': 'كافٍ',
    'telc.grade.failed': 'غير ناجح',
    
    // Study Plan
    'telc.studyPlan.todayLearn': 'تعلم اليوم',
    'telc.studyPlan.examDate': 'امتحان TELC B2',
    'telc.studyPlan.dailyGoal': 'الهدف اليومي',
    'telc.studyPlan.tasksCompleted': 'المهام المنجزة',
    'telc.studyPlan.thisWeek': 'هذا الأسبوع',
    'telc.studyPlan.recommendedExercises': 'التمارين الموصى بها',
    'telc.studyPlan.mockExam': 'امتحان تجريبي',
    
    // Progress Cards
    'telc.progressCard.advanced': 'متقدم',
    'telc.progressCard.intermediate': 'جيد',
    'telc.progressCard.beginner': 'مبتدئ',
    'telc.progressCard.newStart': 'ابدأ جديد',
    'telc.progressCard.bestScore': 'أفضل درجة',
    
    // Tips
    'telc.tips.example': 'مثال:',
    
    // Audio
    'audio.play': 'تشغيل الصوت',
    'audio.stop': 'إيقاف الصوت',
    'audio.pause': 'إيقاف مؤقت',
    'audio.loading': 'جاري تحميل الصوت...',
    
    // Learning German - Always keep visible
    'learningGerman': 'تعلم الألمانية',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
